table FactInternetSales
	lineageTag: e63e3006-4fe9-40a8-b740-c301d0ac632e
	sourceLineageTag: [dbo].[FactInternetSales]

	measure 'Sales Amount' = ```
			
			SUMX(
			    'FactInternetSales',
			    'FactInternetSales'[OrderQuantity] * FactInternetSales[UnitPrice]
			)
			
			```
		lineageTag: 68888d9d-5ca3-4b20-a81e-d20b0ce54023

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ProductKey
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 3c9bc2ec-ce8b-48c6-856d-8211594cc7dc
		sourceLineageTag: ProductKey
		summarizeBy: none
		sourceColumn: ProductKey

		annotation SummarizationSetBy = Automatic

	column OrderDateKey
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: cb25a2e5-d2a2-4589-89f0-ce19be97085d
		sourceLineageTag: OrderDateKey
		summarizeBy: none
		sourceColumn: OrderDateKey

		annotation SummarizationSetBy = Automatic

	column DueDateKey
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 05e1ab32-0982-4d14-a0c5-967c9efb1ba8
		sourceLineageTag: DueDateKey
		summarizeBy: count
		sourceColumn: DueDateKey

		annotation SummarizationSetBy = Automatic

	column ShipDateKey
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: e66686fb-ef35-487b-834b-3a514c940658
		sourceLineageTag: ShipDateKey
		summarizeBy: count
		sourceColumn: ShipDateKey

		annotation SummarizationSetBy = Automatic

	column CustomerKey
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 1428e4a9-ee28-4ac7-8317-45cc1a256782
		sourceLineageTag: CustomerKey
		summarizeBy: none
		sourceColumn: CustomerKey

		annotation SummarizationSetBy = Automatic

	column SalesOrderNumber
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 56264f00-5492-4899-bf10-fbc5aa0691a2
		sourceLineageTag: SalesOrderNumber
		summarizeBy: none
		sourceColumn: SalesOrderNumber

		annotation SummarizationSetBy = Automatic

	column OrderQuantity
		dataType: int64
		formatString: 0
		sourceProviderType: smallint
		lineageTag: eb7cd98b-a7e2-4ad9-ae12-5a2df2b53315
		sourceLineageTag: OrderQuantity
		summarizeBy: sum
		sourceColumn: OrderQuantity

		annotation SummarizationSetBy = Automatic

	column UnitPrice
		dataType: double
		sourceProviderType: decimal(19, 4)
		lineageTag: 34533068-a4f3-459c-9644-a7410e2c3448
		sourceLineageTag: UnitPrice
		summarizeBy: sum
		sourceColumn: UnitPrice

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column UnitPriceDiscountPct
		dataType: double
		sourceProviderType: float
		lineageTag: 22a024ca-0589-4168-982a-7062021b077c
		sourceLineageTag: UnitPriceDiscountPct
		summarizeBy: sum
		sourceColumn: UnitPriceDiscountPct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ProductStandardCost
		dataType: double
		sourceProviderType: decimal(19, 4)
		lineageTag: 4f5bb59f-cee1-41d6-bb3a-d875e9307864
		sourceLineageTag: ProductStandardCost
		summarizeBy: sum
		sourceColumn: ProductStandardCost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition FactInternetSales = entity
		mode: directLake
		source
			entityName: FactInternetSales
			schemaName: dbo
			expressionSource: DatabaseQuery

	annotation PBI_ResultType = Table

